# This file is used just for exposing host ports for local Docker Compose development
# Competitors: You may modify this file to make local development easier.
# However, this file will not impact services at competition, only local development.

---
services:
  dind:
    ports:
      - "2375:2375"
  iapi:
    ports:
      - "8080:8080"
  capi:
    ports:
      - "8082:8080"
    volumes:
      - type: bind
        source: ${PWD}/capi_logs
        target: /var/log/capi
        bind:
          propagation: rshared
      - type: bind
        source: ${PWD}/cp_root
        target: /cp_root
        bind:
          propagation: rshared
  db:
    ports:
      - "5432:5432"
  litellm:
    ports:
      - "8081:80"
