# This file is used just for exposing host ports for local Docker Compose development
# Competitors: You may modify this file to make local development easier.
# However, this file will not impact services at competition, only local development.

# We recommend you only bind ports to 127.0.0.1 in this file & have a GitHub action checking this.
# If you need to bind to other interfaces, putting a comment in this file containing only "exposed-port-check: disable" will turn off that check.

---
services:
  dind:
    #  deploy:
    #    resources:
    #      limits:
    #        cpus: '8'
    #        memory: 8GB
    #      reservations:
    #        cpus: '1'
    #        memory: 256M
    #  ports:
    #    - "127.0.0.1:2375:2375"
    volumes:
      - type: bind
        source: ${PWD}/dind_cache
        target: /var/lib/docker
        bind:
          propagation: rprivate
  load-cp-images:
    restart: "no"
    depends_on:
      - dind
  crs:
    restart: "no"
    volumes:
      - type: bind
        source: ${PWD}/crs/src/py/
        target: /app/py/
        bind:
          propagation: rshared
    depends_on:
      litellm:
        condition: service_healthy
      load-cp-images:
        condition: service_completed_successfully
    # command: ["tail", "-f", "py/run.py"]  # useful to keep CRS container alive in conjunction with `make crs-shell`
    networks:
      - crs-internal
      - internet  # only to be used for langsmith during local CRS run
    env_file:
      - path: ./crs/src/env
        required: false
  # db:
  #   ports:
  #     - "127.0.0.1:5432:5432"
  litellm:
    ports:
      - '127.0.0.1:8081:80'
