[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "Linux"
reportMissingTypeStubs = true
exclude = ["typings"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = true
skip_gitignore = true
known_first_party = ["api", "pipeline", "config", "logger"]

[tool.black]
target-version = ["py310"]
line_length = 120
unstable = true
