[project]
name = "benchmark"
version = "0.1.0"
dependencies = [
    "aioshutil==1.4",
    "aiorwlock==1.4.0",
    "PyYAML==6.0.2",
    "GitPython==3.1.43",
    "langchain==0.3.9",
    "langchain-community==0.3.8",
    "langchain-openai==0.2.10",
    "langgraph==0.2.53",
]

[project.optional-dependencies]
dev = [
    "pip-tools",
    "pyright",
    "black==24.10.0",
    "isort==5.13.2",
    "pre-commit",
    "types-PyYAML",
    "types-requests",
]

[build-system]
requires = ["setuptools", "wheel"]

[tool.pip-tools]
generate-hashes = true

[tool.pyright]
pythonVersion = "3.12"
pythonPlatform = "Linux"
reportMissingTypeStubs = true
exclude = ["typings"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = true
skip_gitignore = true
known_first_party = ["api", "pipeline", "config", "logger"]

[tool.black]
target-version = ["py312"]
line_length = 120
preview = true
enable-unstable-feature= ["hug_parens_with_braces_and_square_brackets"]
