---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crs
resources:
  - resources.yaml
  - service-account.yaml
  - service-role.yaml
  - service-role-binding.yaml

patches:
  - path: load-cp-images-config.json
    target:
      kind: Pod
      name: load-cp-images

configMapGenerator:
  - name: cp-config
    files:
      - configs/cp_config.yaml
    options:
      disableNameSuffixHash: true
