---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crs
resources:
  - resources.yaml
patches:
  - path: load-cp-images-config.json
    target:
      kind: Deployment
      name: load-cp-images

configMapGenerator:
  - name: cp-config
    files:
      - cp_config.yaml
    options:
      disableNameSuffixHash: true
