---
# create a Role Binding, or the connection between a Service Account and a Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crs
subjects:
  - kind: ServiceAccount
    name: crs
