name: CRS Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  crs-action:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install test requirements
        run: pip3 install -r sandbox/crs/requirements.txt -r sandbox/crs/requirements-dev.txt

      - uses: jakebailey/pyright-action@v2
        with:
          working-directory: sandbox/crs/src
      - name: isort
        if: always()
        run: |
          isort sandbox/crs/src --check --diff
      - name: black
        if: always()
        run: |
          black sandbox/crs/src --check --diff